- name: Recover latest backup
  hosts: nfs
  become: true
  environment:
    BORG_PASSPHRASE: secret
  vars:
    borg_repo: 10.10.1.141:/var/backup
    data_dir: /opt/cms/data

  tasks:
    - name: get latest backup
      ansible.builtin.shell: "borg list borg@{{ borg_repo }} | tail -n 1 | awk '{print $1}'"
      become_user: borg
      register: latest_backup

    - debug: msg={{ latest_backup.stdout }}

    - name: Remove old data
      ansible.builtin.file:
        path: "{{ data_dir }}"
        state: absent

    - name: extract backup to cms data dir
      ansible.builtin.command: "borg extract borg@{{ borg_repo }}::{{ latest_backup.stdout }}"
      args:
        chdir: /
      become_user: borg

    - name: Share data directory for nobody
      ansible.builtin.file:
        path: "{{ data_dir }}"
        state: directory
        owner: nobody
        group: nobody
        recurse: yes
        mode: '0777'

